CREATE DATABASE IF NOT EXISTS banca;
USE banca;

CREATE TABLE CITTA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NomeCitta VARCHAR(100) NOT NULL,
    Cap CHAR(5) NOT NULL
);

CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Cognome VARCHAR(100) NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Sesso CHAR(1) NOT NULL
);

CREATE TABLE CONTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Saldo DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE MOVIMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Datam DATE NOT NULL,
    Causale VARCHAR(255) NOT NULL,
    Importo DECIMAL(10,2) NOT NULL
);
